[config]
# This is the path to your documents directory with car setup exports from the garage.
setups_path = ''

# Acceptable theme values are "dark", "light", and "auto".
theme = "auto"

[window]


# Below are the track and car names that will be displayed in the UI and CSV exports. You can update
# these settings to change the appearance, or add new ones without the need for an application
# upgrade when new tracks and cars are added to iRacing.

# Unique IDs for tracks are constructed by taking directory names from the `{setups_path}/lapfiles/`
# directory. Use the longest common prefix for the track (without the track configuration
# identifier). And finally replacing spaces with underscores.

# These are the mappings for unique track identifiers to full names.
[tracks]
charlotte = "[Legacy] Charlotte Motor Speedway - 2008"
charlotte_2018 = "Charlotte Motor Speedway"
concordhalf = "Concord Speedway"
daytona = "[Legacy] Daytona Internal Speedway - 2008"
lagunaseca = "WeatherTech Raceway at Laguna Seca"
lakeland = "USA International Speedway"
langley = "Langley Speedway"
lanier = "Lanier National Speedway"
limaland = "Limaland Motorsports Park"
limerock = "[Legacy] Lime Rock Park - 2008"
limerock_2019 = "Lime Rock Park"
okayama = "Okayama International Raceway"
oran = "Oran Park Raceway"
oulton = "Oulton Park Circuit"
oxford = "Oxford Plains Speedway"
phoenix = "[Legacy] Phoenix Raceway - 2008"
skidpad = "Centripetal Circuit"
southboston = "South Boston Speedway"
southernnational = "Southern Nation Motorsports Park"
summit = "Summit Point Raceway"
thompson = "Thompson Speedway Motorsports Park"
tsukuba = "Tsukuba Circuit"
watkinsglen = "Watkins Glen International"

# Unique IDs for cars are constructed by taking directory names from the `{setups_path}/setups/`
# directory and replacing spaces with underscores.

# These are the mappings for unique car identifiers to full names.
[cars]
astonmartin_dbr9 = "Aston Martin DBR9 GT1"
audi90gto = "Audi 90 GTO"
audir18 = "Audi R18"
audir8gt3 = "Audi R8 LMS"
audirs3lms = "Audi RS 3 LMS"
bmwm4gt3 = "BMW M4 GT3"
bmwm4gt4 = "BMW M4 GT4"
bmwm8gte = "BMW M8 GTE"
bmwz4gt3 = "[Legacy] BMW Z4 GT3"
c6r = "Chevrolet Corvette C6.R GT1"
c7vettedp = "Chevrolet Corvette C7 Daytona Prototype"
c8rvettegte = "Chevrolet Corvette C8.R GTE"
cadillacctsvr = "Cadillac CTS-V Racecar"
dallara = "[Legacy] Indycar Dallara - 2009"
dallaradw12 = "[Legacy] Dallara DW12"
dallaraf3 = "Dallara F3"
dallarair01 = "Dallara iR-01"
dallarair18 = "Dallara IR18"
dallarap217 = "Dallara P217"
dirtstreetstock = "Dirt Street Stock"
dirtumpmod = "Dirt UMP Modified"
ferrari488gt3 = "Ferrari 488 GT3"
ferrari488gte = "Ferrari 488 GTE"
fordfiestarswrc = "Ford Fiesta RS WRC"
fordgt = "Ford GT GT2/GT3"
fordgt_gt3 = "Ford GT GT3"
fordgt2017 = "Ford GTE"
fordv8sc = "[Legacy] V8 Supercar Ford Falcon - 2009"
formulamazda = "[Legacy] Pro Mazda"
formularenault20 = "Formula Renault 2.0"
formularenault35 = "Formula Renault 3.5"
formulavee = "Formula Vee"
fr500s = "Ford Mustang FR500S"
hpdarx01c = "HPD ARX-01c"
indypropm18 = "Indy Pro 2000 PM-18"
jettatdi = "VW Jetta TDI Cup"
kiaoptima = "Kia Optima"
lamborghinievogt3 = "Lamborghini Hurac√°n GT3 EVO"
latemodel = "Dirt Late Model"
legends_dirtford34c = "Dirt Legends Ford '34 Coupe"
legends_ford34c = "Legends Ford '34 Coupe"
legends_ford34c_rookie = "Legends Ford '34 Coupe - Rookie"
lotus49 = "Lotus 49"
lotus79 = "Lotus 79"
mclaren570sgt4 = "McLaren 570S GT4"
mclarenmp4 = "McLaren MP4-12C GT3"
mclarenmp430 = "McLaren MP4-30"
mercedesamggt3 = "Mercedes AMG GT3"
mx5_cup = "[Legacy] Mazda MX-5 Cup - 2010"
mx5_mx52016 = "Global Mazda MX-5 Cup"
mx5_roadster = "[Legacy] Mazda MX-5 Roadster - 2010"
nissangtpzxt = "Nissan GTP ZX-T"
porsche718gt4 = "Porsche 718 Cayman GT4 Clubsport MR"
porsche911cup = "Porsche 911 GT3 Cup (991)"
porsche911rgt3 = "Porsche 911 GT3 R"
porsche919 = "Porsche 919"
porsche991rsr = "Porsche 911 RSR"
protrucks_pro2lite = "Lucas Oil Off Road Pro 2 Lite"
protrucks_pro2truck = "Lucas Oil Off Road Pro 2 Truck"
protrucks_pro4truck = "Lucas Oil Off Road Pro 4 Truck"
radical_sr8 = "Radical SR8"
rileydp = "[Legacy] Riley MkXX Daytona Prototype - 2008"
rufrt12r_awd = "Ruf RT 12R AWD"
rufrt12r_rwd = "Ruf RT 12R RWD"
rufrt12r_track = "Ruf RT 12R Track"
rufrt12r_track_cspec = "Ruf RT 12R C-Spec"
rt2000 = "Skip Barber Formula 2000"
silvercrown = "Silver Crown"
skmodified_tour = "NASCAR Whelen Tour Modified"
solstice = "Pontiac Solstice"
solstice_rookie = "Pontiac Solstice - Rookie"
specracer = "SCCA Spec Racer Ford"
sprint = "Sprint Car"
stockcars_camarozl12018 = "NASCAR Cup Series Chevrolet Camaro ZL1"
stockcars_chevycamarozl12022 = "NASCAR Cup Series Next Gen Chevrolet Camaro ZL1"
stockcars_chevymontecarlo87 = "NASCAR Chevrolet Monte Carlo - 1987"
stockcars_chevyss = "[Legacy] NASCAR Cup Chevrolet SS - 2013"
stockcars_fordfusion = "[Legacy] NASCAR Cup Ford Fusion - 2016"
stockcars_fordmustang2019 = "NASCAR Cup Series Ford Mustang"
stockcars_fordmustang2022 = "NASCAR Cup Series Next Gen Ford Mustang"
stockcars_fordthunderbird87 = "NASCAR Ford Thunderbird - 1987"
stockcars_impala = "[Legacy] NASCAR Cup Chevrolet Impala COT - 2009"
stockcars_toyotacamry = "NASCAR Cup Series Toyota Camry"
stockcars_toyotacamry2022 = "NASCAR Cup Series Next Gen Toyota Camry"
stockcars2_camaro2019 = "NASCAR Xfinity Chevrolet Camaro"
stockcars2_camry2015 = "[Legacy] NASCAR Xfinity Toyota Camry - 2015"
stockcars2_chevy_cot = "[Legacy] NASCAR Nationwide Chevrolet Impala - 2012"
stockcars2_mustang2019 = "NASCAR Xfinity Ford Mustang"
stockcars2_nwcamaro2014 = "[Legacy] NASCAR Xfinity Chevrolet Camaro - 2014"
stockcars2_nwford2013 = "[Legacy] NASCAR Xfinity Ford Mustang - 2016"
stockcars2_supra2019 = "NASCAR Xfinity Toyota Supra"
streetstock = "Street Stock"
subaruwrxsti = "Subaru WRX STI"
superlatemodel = "Super Late Model"
trucks_fordf150 = "NASCAR Gander Outdoors Ford F150"
trucks_silverado = "[Legacy] NASCAR Truck Chevrolet Silverado - 2008"
trucks_silverado2019 = "NASCAR Gander Outdoors Chevrolet Silverado"
trucks_tundra2015 = "NASCAR Gander Outdoors Toyota Tundra"
usf2000usf17 = "USF 2000"
v8supercars_ford2014 = "[Legacy] V8 Supercar Ford FG Falcon - 2014"
v8supercars_fordmustanggt = "Supercars Ford Mustang GT"
v8supercars_holden2014 = "[Legacy] V8 Supercar Holden VF Commodore - 2014"
v8supercars_holden2019 = "Supercars Holden ZB Commodore"
vwbeetlegrc = "VW Beetle"
vwbeetlegrc_lite = "VW Beetle - Lite"
williamsfw31 = "Williams-Toyota FW31"
